logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ADD-YOUR-CONFIGURATION
            client-secret: ADD-YOUR-CONFIGURATION
            scope: openid, profile
          github:
            client-id: ADD-YOUR-CONFIGURATION
            client-secret: ADD-YOUR-CONFIGURATION